package edu.ptithcm.configs;

public enum TypeDTTP {
    //authentication type
    LOGIN("LOGIN"),
    LOGOUT("LOGOUT"),
    FORCE_KICK("FORCE_KICK"),
    //employee type
    EMPLOYEE_GET_ALL("EMPLOYEE_GET_ALL"),
    EMPLOYEE_CREATE("EMPLOYEE_CREATE"),
    EMPLOYEE_GET_ACTIVE("EMPLOYEE_GET_ACTIVE"),
    EMPLOYEE_UPDATE("EMPLOYEE_UPDATE"),
    EMPLOYEE_DELETE("EMPLOYEE_DELETE"),
    EMPLOYEE_FILTER("EMPLOYEE_FILTER"),
    //product type
    PRODUCT_GET_ALL("PRODUCT_GET_ALL"),
    PRODUCT_CREATE("PRODUCT_CREATE"),
    PRODUCT_UPDATE("PRODUCT_UPDATE"),
    PRODUCT_DELETE("PRODUCT_DELETE"),

    //category type
    CATEGORY_GET_ALL("CATEGORY_GET_ALL"),
    CATEGORY_CREATE("CATEGORY_CREATE"),
    CATEGORY_UPDATE("CATEGORY_UPDATE"),
    CATEGORY_DELETE("CATEGORY_DELETE"),

    //inventory type
    INVENTORY_GET_ALL("INVENTORY_GET_ALL"),
    INVENTORY_CREATE("INVENTORY_CREATE"),
    INVENTORY_UPDATE("INVENTORY_UPDATE"),
    INVENTORY_DELETE("INVENTORY_DELETE"),

    //branch type
    BRANCH_GET_ALL("BRANCH_GET_ALL"),
    BRANCH_CREATE("BRANCH_CREATE"),
    BRANCH_UPDATE("BRANCH_UPDATE"),
    BRANCH_DELETE("BRANCH_DELETE"),
    BRANCH_GET_BY_ID("BRANCH_GET_BY_ID"),

    //customer type
    CUSTOMER_GET_ALL("CUSTOMER_GET_ALL"),
    CUSTOMER_CREATE("CUSTOMER_CREATE"),
    CUSTOMER_UPDATE("CUSTOMER_UPDATE"),
    CUSTOMER_DELETE("CUSTOMER_DELETE"),
    CUSTOMER_GET_BY_PHONE("CUSTOMER_GET_BY_PHONE"),

    // invoice type
    INVOICE_GET_ALL("INVOICE_GET_ALL"),
    INVOICE_CREATE("INVOICE_CREATE"),
    INVOICE_UPDATE("INVOICE_UPDATE"),
    INVOICE_DELETE("INVOICE_DELETE"),
    INVOICE_GET_BY_CUSTOMER("INVOICE_GET_BY_CUSTOMER"),
    INVOICE_GET_BY_BRANCH("INVOICE_GET_BY_BRANCH"),
    INVOICE_GET_BY_EMPLOYEE("INVOICE_GET_BY_EMPLOYEE"),

    // loyalty
    LOYALTY_GET_ALL("LOYALTY_GET_ALL"),
    LOYALTY_GET_BY_CUSTOMER("LOYALTY_GET_BY_CUSTOMER"),
    LOYALTY_CREATE("LOYALTY_CREATE"),
    LOYALTY_UPDATE("LOYALTY_UPDATE"),
    LOYALTY_DELETE("LOYALTY_DELETE"),

    //System
    PING("PING"),
    PING_RESPONSE("PING_RESPONSE");

    private final String value;

    TypeDTTP(String value) {
        this.value = value;
    }

    public String getValue() {
        return this.value;
    }
}